### ISSUE TITLE
null

### ISSUE THREAD

**Issue by ng4ever** [Cito/Pinboard-Pin#18]
I keep getting null when saving links with Pinboard+
https://addons.mozilla.org/en-US/firefox/addon/pinboard-plus/?src=search

It is in Pushpin for iOS. Should I be contacting the developer of Pushpin or is it a Pinboard+ issue?

The reason I ask is right now I am using a different Pinboard Firefox addon and it works fine without null on Pushpin. 

If you need any examples just let me know. Thanks.

**Comment by Cito** [comment]
What do you mean with "getting null"? Also, Pushpin for Pinboard and Pinboard+ are different extensions. This is the issue tracker for [Pinboard Pin](https://addons.mozilla.org/de/firefox/addon/pinboard-pin/).

**Comment by ng4ever** [comment]
> 
> 
> What do you mean with "getting null"? Also, Pushpin for Pinboard and Pinboard+ are different extensions. This is the issue tracker for [Pinboard Pin](https://addons.mozilla.org/de/firefox/addon/pinboard-pin/).

Sorry this. 

![IMG_0037](https://user-images.githubusercontent.com/17295139/65454206-3f076800-de0a-11e9-8940-a32cd2df3925.PNG)

When I go to click on the link it won't open. This is with saving the link from Pinboard Pin addon

**Comment by Cito** [comment]
So do I understand this correctly? You were saving the link with Pinboard Pin and then showing it in Pushpin, but Pushpin shows "(null)" instead of the URL. Is this right?

Just tried to reproduce this with an Amazon link, but it works for me.

* When you log in to https://pinboard.in, and edit the link, is the URL displayed?
* Is this problem permanent? Can you reproduce it?
* Does it happen with all links or only certain URLs? In this case, can you the exact URL that you pinned?
* Which Firefox version on which OS are you using? Are there any other AddOns which might interfere?

**Comment by ng4ever** [comment]
> 
> 
> So do I understand this correctly? You were saving the link with Pinboard Pin and then showing it in Pushpin, but Pushpin shows "(null)" instead of the URL. Is this right?
> 
> Just tried to reproduce this with an Amazon link, but it works for me.
> 
>     * When you log in to https://pinboard.in, and edit the link, is the URL displayed?
> 
>     * Is this problem permanent? Can you reproduce it?
> 
>     * Does it happen with all links or only certain URLs? In this case, can you the exact URL that you pinned?
> 
>     * Which Firefox version on which OS are you using? Are there any other AddOns which might interfere?

Yes you are understanding me correctly.

- Yes

- Yes I believe so

- Only certain URLs as far as I can tell sorry

- Firefox 69.0.1 and Windows 10 Pro. Maybe I will have to check.

Thanks for trying!

**Comment by Cito** [comment]
Ok, great. Had been trying with the same Firefox version on Windows.

If you post an exact URL that can reproduce the error, I can try again with that URL. But since it shows properly in the Pinboard service, it looks like Pinboard Pin has stored it correctly so it must be actually  a Pushpin issue.

**Comment by ng4ever** [comment]
> 
> 
> Ok, great. Had been trying with the same Firefox version on Windows.
> 
> If you post an exact URL that can reproduce the error, I can try again with that URL. But since it shows properly in the Pinboard service, it looks like Pinboard Pin has stored it correctly so it must be actually a Pushpin issue.


Ok thanks. I will alert the Pushpin developer to the issue and see if they can determine the cause of the issue.

Thanks again!
