### ISSUE TITLE
"Add bookmark" button disabled on some pages

### ISSUE THREAD

**Issue by davidag** [Cito/Pinboard-Pin#19]
On some web pages, the "Add bookmark" button is disabled and you are unable to use the plugin. You have to use the web interface, which works correctly.

Example URLs:
- <https://twitter.com/r00k/status/1175100703829909505>

**Comment by Cito** [comment]
Thanks for reporting. Found the problem: The title is > 255 chars long (it's the full tweet which can have up to 280 chars nowadays) but the title may according to the specs of the Pinboard API only be 255 chars long (even though the web interface happily accepts it). That's why it's considered invalid in the form and the button is disabled. I will change this to automatically trim the title to 255 chars if it's too long.

**Comment by Cito** [comment]
The fix is now available in v0.2.9.

**Comment by davidag** [comment]
Thank you Cito! That was fast! 🎉
