### ISSUE TITLE
New CSS is low contrast, not configurable, and a bit garish

### ISSUE THREAD

**Issue by lostfictions** [Cito/Pinboard-Pin#27]
Hi again, I noticed the CSS for this extension changed recently. I appreciate the attempts to give the popup a bit of a facelift, but the purple-on-purple look is quite difficult to read ([aremycoloursaccessible.com](https://www.aremycoloursaccessible.com/) ranks it as 6.34:1, which is a passing grade but not ideal for small text). I see that there seems to be a light version based on the screenshots in the repo, so I imagine that this might be based on `prefers-color-scheme` and is interpreting that I'm in dark mode? It would be really great if there were a way to configure this manually -- perhaps a configuration called "colour scheme" with options "light", "dark", and "auto", where "auto" is the current behaviour?

As an aside, the new CSS also seems to add a horizontal scrollbar on the popup for some reason:

![Screenshot from 2020-08-24 07-34-22](https://user-images.githubusercontent.com/567041/91040900-04d7b500-e5dd-11ea-98b3-71e1941326b4.png)

**Comment by Cito** [comment]
Yes, it's using `prefers-color-scheme`. I'll look if I can make this configurable with the three options you suggested.

I don't want to make the theme configurable though, that would be too much work, and few people would want to bother with that. Maybe we can just make the colors a bit more accessible while keeping it nice. If you or @rbeeger have any suggestions for a more accessible color scheme let me know. Otherwise I'll look if I can simply steel from some popular scholor scheme on the Internet. Maybe we can also make the button texts a little bit larger.

Regarding the horizontal scrollbar issue, it doesn't happen for me. Which FF version are you using, on which platform?

**Comment by lostfictions** [comment]
This is on FF79, in Ubuntu 20.04 (just vanilla Gnome Shell)

**Comment by rbeeger** [comment]
In the screenshot it looks a bit strange that the `textarea` for the description seems to take up more space horizontally than the `input`s above and below. Don't see that on macOS and haven't seen it on windows 10, but the same browser version often has some subtle differences in layout handling on different platforms. And the `textarea` doesn't have a completely custom css. The resize handle - on macOS in the lower right corner - is probably native and may have some effect on the size of the textarea.

As for the dark mode theme: I don't really insist on any colors that are used there. I myself only use the light mode theme. Just added a dark mode theme because it seemed like a good idea to have one, but I really didn't do any longtime tests with it. 
The simplest way to fix it would probably be to replace the purple text color with the white color used in the labels for the inputs. But I'm fine with any other dark mode theme you come up with.

**Comment by Cito** [comment]
Thanks for the feedback. I was able to reproduce the horizontal scrollbar issue on Ubuntu and I also think it has to do with the textarea. Will look into this when I find some more time.

**Comment by Cito** [comment]
This should now be better in v0.4.0.

I also made the theme a bit easier to modify by using SCSS and CSS variables.

**Comment by lostfictions** [comment]
@Cito much improved imo, thanks for your work on this!
