### ISSUE TITLE
ER: Binding a hotkey

### ISSUE THREAD

**Issue by emory** [Cito/Pinboard-Pin#6]
Enhancement request: Bind a hotkey for sending current page to Pinboard (e.g. command+shift+D, option+/alt+p)

**Comment by Cito** [comment]
Thanks for the suggestion. I'll consider this for the next update. Should be easy to implement.

**Comment by Cito** [comment]
Another request via mail: One thing I want to ask you about the add-on is the “keyboard shortcut”. I find some of other add-ons made “Alt+P” as a keyboard shortcut for adding a new bookmark. And I was wondering if your add-on could do the same.

**Comment by tonycpsu** [comment]
+1 on this.  Ideally, we'd be able to have separate keys for "just pin it with my default settings and don't ask me anything" vs. "pop up a dialog with tags, private checkbox, read it later checkbox, etc."

**Comment by Cito** [comment]
So I have now implemented this in Version 0.2.5. There are two caveats, though:

1. Currently I see no way to change or deactivate the default keyboard shortcut Alt+P - it seems this cannot be easily implemented with the new WebExt API. If you know any trick to do this, or any open source extensions where a global shortcut is configurable, so that I can look at the code, let me know.
2. Currently, when opening the popup using the keyboard shortcut, it does not have focus - i.e. you first need to click somewhere into the popup. This seems to be a bug in the current Firefox versions, as it works in Firefox Nightly (Version 60). Here Ctrl+P + Enter can be used to quickly save a bookmark.
3. I might add the suggested "save without asking" when I find a way to make it configurable. Maybe Ctrl+P + Enter is a good enough solution anyway.
