### ISSUE TITLE
Sorting by tag count not quite working right

### ISSUE THREAD

**Issue by andrewducker** [Cito/Pinboard-Pin#9]
Sometimes it seems to work and other times not.  Are you sure it's treating the tag count as numbers correctly - because it _could_ be sorting by the first digit of the tag count (or by sorting them as strings?)

**Comment by Cito** [comment]
It works for me, and I just double checked that the tag frequencies are really used as numbers, not strings.

The only small problem in the current version is that it caches the tag counts in local storage and updates the cache only every hour. In between, tag counts in the cache are updated manually, but that update storage does not work properly - it only increases tag counts, and never decreases it. I have now fixed this update mechanism and it should work properly now in the next version.

Also, please note that the tag list appears *above* the input field (I think I made it so because I didn't want it to hide the suggested tags), therefore I also reversed the sort order. I wanted the tags with highest counts to appear on the *bottom* of the list, the tags with lower frequences at the *top*. That way the most frequent, preselected tag appears directly above the input field. Maybe you weren't expecting this reversed sorting order?

**Comment by andrewducker** [comment]
I give up!  I just reloaded it (on this page) and typed "UK", expecting it to do the same as it did earlier (sorting UK and UKIP the wrong way around) - and it's now sorting it correctly.

So I don't know if I just wasn't waiting long enough.  Or I was doing something else wrong.

Sorry for wasting your time!

**Comment by Cito** [comment]
At least you helped me fixing the code for proper updating tag counts in the cache. Just published the bugfix release. Please reopen if you still see the problem.
